name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Prepare Project Structure & Dependencies
        run: |
          mkdir -p backup_code
          if [ -f main.dart ]; then cp main.dart backup_code/; fi
          flutter create . --overwrite
          if [ -f backup_code/main.dart ]; then cp backup_code/main.dart lib/main.dart; fi
          flutter pub add shared_preferences crypto

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WesamPhone-App
          path: build/app/outputs/flutter-apk/app-release.apk
